version: '3.9'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - ./postgress-persist:/var/lib/postgresql/data
    networks:
      - spring-keycloak-network
  keycloak:
    image: bitnami/keycloak
    restart: always
    container_name: keycloak
    depends_on:
      - postgres
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak
      KEYCLOAK_EXTRA_ARGS: --import-realm
    volumes:
      - ./keycloak-realm:/opt/bitnami/keycloak/data/import
    ports:
      - "8080:8080"
    networks:
      - spring-keycloak-network
networks:
  spring-keycloak-network:
    driver: bridge
